# Base configs
baseurl: "/profileflat/"

# UI configs
title: "Nitin Lalwani"
author: "Nitin Lalwani"
about: "Watching world through my camera."
social_urls:
  facebook: "https://www.facebook.com/nitin.lalwani.334"
  twitter: "#"
  instagram: "https://www.instagram.com/nitinlalwani02/"
