# Base configs
baseurl: "/profileflat/"

# UI configs
title: "Nitin Lalwani"
author: "Nitin Lalwani"
about: "Watching world through my camera."
social_urls:
  facebook: "#"
  twitter: "#"
  instagram: "#"
